#!/usr/bin/env bash

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  open https://github.com/account/ssh

echo "Installing Homebrew..."
  ruby -e "$(curl -fsSL https://gist.github.com/raw/323731/install_homebrew.rb)"
  brew update

echo "Installing git..."
  brew install git

echo "Installing MySQL..."
  brew install mysql

echo "Installing Redis..."
  brew install redis

echo "Installing ack..."
  brew install ack

echo "Installing MacVim..."
  brew install macvim

echo "Installing ctags..."
  brew install ctags

echo "Installing tig..."
  brew install tig

echo "Installing tmux..."
  brew install tmux

echo "Installing wget..."
  brew install wget

echo "Installing zsh..."
  brew install zsh

echo "Installing ImageMagick..."
  brew install imagemagick

echo "Installing RVM (Ruby Version Manager) ..."
  curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version latest
  echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.zshrc
  source ~/.zshrc

bash < <(curl -s https://raw.github.com/beerlington/laptop/master/ruby)
